name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us identify and fix the issue.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the documentation
          required: true
        - label: I am using the latest version
          required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Connect device '...'
        3. Execute tool '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you using?
      multiple: true
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true

  - type: dropdown
    id: device-type
    attributes:
      label: Device Type
      description: What type of device are you testing with?
      multiple: true
      options:
        - Android Physical Device
        - Android Emulator
        - iOS Physical Device
        - iOS Simulator
        - None (server issue)
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust Version
      description: Output of `rustc --version`
      placeholder: "rustc 1.70.0 (90c541806 2023-05-31)"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Mobile Device MCP Version
      description: Which version are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: mode
    attributes:
      label: Execution Mode
      description: How are you running the server?
      options:
        - Native Binary (standalone)
        - Zed Extension (WASM)
        - Both
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Additional environment information
      placeholder: |
        - ADB version:
        - Xcode version (macOS only):
        - Device ID:
        - Device OS version:
      render: markdown

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Relevant logs, error messages, or stack traces
      placeholder: |
        Paste logs here...

        Run with MOBILE_DEVICE_MCP_DEBUG=1 for verbose output
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant configuration or MCP request payload
      placeholder: |
        {
          "jsonrpc": "2.0",
          "method": "tools/call",
          "params": {...}
        }
      render: json

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem
      placeholder: Drag and drop images here or paste image URLs

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Have you found a workaround for this issue?
      placeholder: Describe any workarounds...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other relevant information...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help fix this bug?
      options:
        - label: I would like to work on fixing this bug
          required: false
        - label: I can provide additional testing/debugging
          required: false
